apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: {{ .Base64CACertificate }}
    server: {{ .APIServerURL}}:443
  name: {{ .Cluster }}
contexts:
- context:
    cluster: {{ .Cluster }}
    user: {{ .User }}-{{ .Cluster }}
  name: {{ .User }}@{{ .Cluster }}
current-context: {{ .User }}@{{ .Cluster }}
kind: Config
users:
- name: {{ .User }}-{{ .Cluster }}
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1
      command: "{{ .Executable }}"
      args:
{{- range .ExecArgs }}
        - {{ . }}
{{- end }}
      installHint: Install the Thalassa Cloud CLI and authenticate with `tcloud context login`.
      interactiveMode: Never
