version: 2

project_name: tcloud

builds:
  - id: tcloud
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

before:
  hooks:
    - go mod tidy
    - ./scripts/shell-completions.sh

archives:
  - formats: [tar.gz]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - completions/*

dockers_v2:
  - ids: [tcloud]
    dockerfile: Dockerfile
    images:
      - 'ghcr.io/thalassa-cloud/{{ .ProjectName }}'
    tags:
      - 'v{{ .Version }}'
      - latest
    labels:
      org.opencontainers.image.version: '{{ .Version }}'
      org.opencontainers.image.source: '{{ .GitURL }}'
      org.opencontainers.image.title: '{{ .ProjectName }}'
    platforms:
      - linux/amd64
      - linux/arm64

release:
  draft: false

# Documentation: https://goreleaser.com/customization/changelog/
changelog:
  use: github

checksum:
  name_template: 'checksums.txt'
