apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: {{ .Base64CACertificate }}
    server: {{ .APIServerURL}}:443
  name: {{ .Cluster }}
contexts:
- context:
    cluster: {{ .Cluster }}
    user: {{ .User }}-{{ .Cluster }}
  name: {{ .User }}@{{ .Cluster }}
current-context: {{ .User }}@{{ .Cluster }}
kind: Config
users:
- name: {{ .User }}-{{ .Cluster }}
  user:
    token: {{ .SessionToken}}
